# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run test
    - run: npm run test:e2e
    - run: npm run test:cov
    - run: npm run build:test
    - name: Display all folders for debug
      - run: ls
    - name: Display dist/test folder content fot debug
      run: |
        ls dist/test
    # - name: Create temporary file to get MongoDB URI
    #   run: |
    #     echo "const path = require('path');" > getMongoUri.js
    #     echo "const { createMongoMemoryConnection } = require(path.join(process.cwd(), 'dist/test/mongo-memory-connection.provider'));" >> getMongoUri.js
    #     echo "createMongoMemoryConnection().then(({ mongod }) => console.log(mongod.getUri()));" >> getMongoUri.js

    # - name: Set NODE_ENV and MONGODB_URI
    #   run: |
    #     echo "NODE_ENV=gen" >> $GITHUB_ENV
    #     MONGODB_URI="$(node getMongoUri.js)"
    #     echo "MONGODB_URI=$MONGODB_URI" >> $GITHUB_ENV

    # - name: Remove temporary file
    #   run: rm getMongoUri.js

    - name: Build and generate OpenAPI files
      run: npm run open-api-gen

    - name: Copy Swagger files to _site
      run: |
        cp dist/swagger.json _site/swagger.json
        cp dist/swagger.html _site/swagger.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
