# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run test
    - run: npm run test:e2e
    - run: npm run test:cov
    - name: Set NODE_ENV and MONGODB_URI
      run: |
        echo "NODE_ENV=gen" >> $GITHUB_ENV
        echo "MONGODB_URI=$(node -e 'require("../dist/test/mongo-memory-connection.provider").createMongoMemoryConnection().then(({ mongod }) => console.log(mongod.getUri()))')" >> $GITHUB_ENV
    - run: npm run open-api-gen
    - name: Copy Swagger files to _site
      run: |
        cp dist/swagger.json _site/swagger.json
        cp dist/swagger.html _site/swagger.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
